# This template merge config file lists:
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
name = "Word guess game Template"
patterns = ["smj", "Lule Sámi"]
rev_id = 1
required = [".github/workflows/publish.yml",
            ".gitignore",
            ".husky/.gitignore",
            ".husky/pre-commit",
            ".prettierrc",
            ".vscode/settings.json",
            "package.json",
            "postcss.config.js",
            "public/favicon.ico",
            "public/index.html",
            "public/locales/en/translation.json",
            "public/locales/es/translation.json",
            "public/locales/sw/translation.json",
            "public/locales/zh/translation.json",
            "public/logo192.png",
            "public/logo512.png",
            "public/manifest.json",
            "public/robots.txt",
            "src/App.css",
            "src/App.test.tsx",
            "src/App.tsx",
            "src/components/alerts/Alert.tsx",
            "src/components/grid/Cell.tsx",
            "src/components/grid/CompletedRow.tsx",
            "src/components/grid/CurrentRow.tsx",
            "src/components/grid/EmptyRow.tsx",
            "src/components/grid/Grid.tsx",
            "src/components/keyboard/Key.tsx",
            "src/components/keyboard/Keyboard.tsx",
            "src/components/mini-grid/MiniCell.tsx",
            "src/components/mini-grid/MiniCompletedRow.tsx",
            "src/components/mini-grid/MiniGrid.tsx",
            "src/components/modals/AboutModal.tsx",
            "src/components/modals/BaseModal.tsx",
            "src/components/modals/InfoModal.tsx",
            "src/components/modals/StatsModal.tsx",
            "src/components/modals/TranslateModal.tsx",
            "src/components/stats/Histogram.tsx",
            "src/components/stats/Progress.tsx",
            "src/components/stats/StatBar.tsx",
            "src/i18n.ts",
            "src/index.css",
            "src/index.tsx",
            "src/lib/keyboard.ts",
            "src/lib/localStorage.ts",
            "src/lib/share.ts",
            "src/lib/stats.ts",
            "src/lib/statuses.ts",
            "src/lib/tokenizer.ts",
            "src/lib/words.ts",
            "src/logo.svg",
            "src/react-app-env.d.ts",
            "src/reportWebVitals.ts",
            "src/setupTests.ts",
            "tailwind.config.js",
            "tsconfig.json"]

optional = ["Dockerfile",
            "LICENSE",
            "README.md",
            "package-lock.json"]

ignored = [ "src/constants/config.ts",
            "src/constants/orthography.ts",
            "src/constants/validGuesses.ts",
            "src/constants/wordlist.ts"]
